//***************************************

#重写名称: 向日葵
#重写作者: RuCu6
#更新时间: 2024-07-12
#仓库地址: https://raw.githubusercontent.com/RuCu6/QuanX/main/Rewrites/MyBlockAds.conf

//***************************************






hostname = client-api-v2.oray.com


^https?:\/\/client-api-v2\.oray\.com\/materials\/(SUNLOGIN_CLIENT_IOS_PROMOTION|SLCC_IOS_DEVICE|SLCC_IOS_STARTUP) url reject-200
